{"asset" : "BINANCEBNBUSDT",
    "bnb_1h_solid_base":{ # Note, this works well at 8 hours for BTC as well
        "Power1": 1.05,
        "Power2": 0.90,
        "Power3": 0.005,
        "fastEMA": 21,
        "slowEMA": 29,
        "fastSMA": 16,
        "slowSMA": 21,
        "trimShort": 2,
        "trimLong": 2,
        },
    "bnb_1h_max_opt":{
        "Power1": 1.485471,
        "Power2": 0.696677,
        "Power3": 0.0027197,
        "fastEMA": 10,
        "slowEMA": 82,
        "fastSMA": 83,
        "slowSMA": 38, # NOTE: This is the slowSMA for the 1h_max_opt however it is actually faster than fast EMA
        "trimShort": 0.1470315,
        "trimLong": 0.07660551,
    },
"asset" : "BINANCESOLUSDT",
    "sol_1h_solid_base":{ # Note, this works well at 8 hours for BTC as well
        "Power1": 1.15,
        "Power2": 0.90,
        "Power3": 0.005,
        "fastEMA": 7,
        "slowEMA": 30,
        "fastSMA": 37,
        "slowSMA": 80,
        "trimShort": 3,
        "trimLong": 3,
        },
}