{"asset" : 
    {"BINANCEBNBUSDT":
        {"bnb_1h_solid_base":
            { 
            "Power1": 1.05,
            "Power2": 0.90,
            "Power3": 0.005,
            "fastEMA": 21,
            "slowEMA": 29,
            "fastSMA": 16,
            "slowSMA": 21,
            "trimShort": 2,
            "trimLong": 2,
            },
        "bnb_1h_max_opt":{
            "Power1": 1.485471,
            "Power2": 0.696677,
            "Power3": 0.0027197,
            "fastEMA": 10,
            "slowEMA": 82,
            "fastSMA": 83,
            "slowSMA": 38, # NOTE: This is the slowSMA for the 1h_max_opt however it is actually faster than fast EMA
            "trimShort": 0.1470315,
            "trimLong": 0.07660551,
            },
        "bnb_1h_good_strat":{
            "Power1": 1.5,
            "Power2": 0.9,
            "Power3": 0.005,
            "fastEMA": 11,
            "slowEMA": 30,
            "fastSMA": 38,
            "slowSMA": 83, 
            "trimShort": 0.03,
            "trimLong": 0.03,
            },
        "bnb_1h_working_strat":{
            "Power1": 1.15,
            "Power2": 0.9,
            "Power3": 0.005,
            "fastEMA": 11,
            "slowEMA": 30,
            "fastSMA": 38,
            "slowSMA": 50, 
            "long/short":on,
            "trimShort": off,
            "trimLong": off,
            },
    },
    "BINANCESOLUSDT":
        {
        "sol_45m_solid_base":{
            "Power1": 1.15,
            "Power2": 0.90,
            "Power3": 0.005,
            "fastEMA": 7,
            "slowEMA": 30,
            "fastSMA": 37,
            "slowSMA": 80,
            "trimShort": 3,
            "trimLong": 3,
            },
        "sol_1h_good_start":{
            "Power1": 1.5,
            "Power2": 0.90,
            "Power3": 0.005,
            "fastEMA": 11,
            "slowEMA": 30,
            "fastSMA": 38,
            "slowSMA": 83,
            "trimShort": 3,
            "trimLong": 3,
            },
        "sol_1h_alternative":{
            "Power1": 1.05,
            "Power2": 0.95,
            "Power3": 0.005,
            "fastEMA": 21,
            "slowEMA": 29,
            "fastSMA": 16,
            "slowSMA": 21,
            "trimShort": 2,
            "trimLong": 2,
            },
        },
    },
}
