{
    "asset" : "BINANCEETHUSDT",
        "eth_2h_low_dd":{
        "start": 0.018, 
        "increment": 0.023, 
        "maximum": 0.3, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 5, 
        "daily profit target change": 3, 
        "order size": 60, 
        "commission": 0.02, 
        "margin long": 50, 
        "margin short": 50
        },
    "eth_2h_first_strat":{
        "start": 0.023, 
        "increment": 0.023, 
        "maximum": 0.3, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 10, 
        "daily profit target change": 5, 
        "order size": 60, 
        "commission": 0.02, 
        "margin long": 50, 
        "margin short": 50
        },
    "eth_90m_first_strat":{
        "start": 0.023, 
        "increment": 0.023, 
        "maximum": 0.23, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 10, 
        "daily profit target change": 5, 
        "order size": 60, 
        "commission": 0.02, 
        "margin long": 50, 
        "margin short": 50,
        },
    "eth_90m_low_freq":{
        "start": 0.02, 
        "increment": 0.023, 
        "maximum": 0.07, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 7, 
        "daily profit target change": 7, 
        "order size": 100, 
        "commission": 0.04, 
        "margin long": 50, 
        "margin short": 50,
        },
    "eth_2h_in_production":{
        "start": 0.02,
        "increment": 0.023,
        "maximum": 0.2, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 7, 
        "daily profit target change": 5, 
        "order size": 100, 
        "commission": 0.04, 
        "margin long": 50, 
        "margin short": 50,
        },
    "BTC_2h_in_production":{
        "start": 0.02,
        "increment": 0.012,
        "maximum": 0.2, 
        "initial trade size": 100, 
        "how many ticks": 100, 
        "take profit change %": 10, 
        "daily profit target change": 7, 
        "order size": 60, 
        "commission": 0.04, 
        "margin long": 30, 
        "margin short": 30,
        },
}
